# Generated by Django 5.2.4 on 2025-07-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_marca', '0001_initial'),
        ('ordem_servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='marca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_marca.marca'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_marca.modelo'),
            preserve_default=False,
        ),
    ]
